const {
    DB_SESSION_SECRET,
    DB_URL,
    DB_ENVIRONMENT,
    DB_PORT,
    USER_EMAIL,
    USER_EMAIL_PASSWORD
} = process.env


module.exports = {
    DATABASE_URL: DB_URL,
    DATABASE_SESESSION_SECRET: DB_SESSION_SECRET,
    DATABASE_ENVIRONMENT: DB_ENVIRONMENT,
    DATABASE_PORT: DB_PORT,
    TOKEN_EXPIRE: 24,
    USER_EMAIL: USER_EMAIL,
    USER_EMAIL_PASSWORD: USER_EMAIL_PASSWORD
};