const { DB_URL, DB_ENVIRONMENT, DB_PORT, RPC_NODE_URL } = process.env;

module.exports = {
  DATABASE_URL: DB_URL,
  DATABASE_ENVIRONMENT: DB_ENVIRONMENT,
  DATABASE_PORT: DB_PORT,
  RPC_NODE_URL,
};
